//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Floristeria.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Floristeria.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1706102_orig {
            get {
                object obj = ResourceManager.GetObject("1706102_orig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1706102_orig1 {
            get {
                object obj = ResourceManager.GetObject("1706102_orig1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap af606cbf7f5250a76c9f05ed123b2bf4_planta_de_flores_planas_delicadas_simples {
            get {
                object obj = ResourceManager.GetObject("af606cbf7f5250a76c9f05ed123b2bf4-planta-de-flores-planas-delicadas-simples", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap af606cbf7f5250a76c9f05ed123b2bf4_planta_de_flores_planas_delicadas_simples1 {
            get {
                object obj = ResourceManager.GetObject("af606cbf7f5250a76c9f05ed123b2bf4-planta-de-flores-planas-delicadas-simples1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d1e19da670d88af2de2b576533d3fd63_icono_de_flores_de_planta_acuarela_delicada {
            get {
                object obj = ResourceManager.GetObject("d1e19da670d88af2de2b576533d3fd63-icono-de-flores-de-planta-acuarela-delicada", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hermoso_contorno_logo_con_rosa_flor_para_boutique_o_salon_de_belleza_o_flores_empresa_rosa_vector_logo_ilustracion_el_logotipo_simple_minimo_facil_t_2f4d9c0 {
            get {
                object obj = ResourceManager.GetObject("hermoso-contorno-logo-con-rosa-flor-para-boutique-o-salon-de-belleza-o-flores-emp" +
                        "resa-rosa-vector-logo-ilustracion-el-logotipo-simple-minimo-facil-t-2f4d9c0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hermoso_contorno_logo_con_rosa_flor_para_boutique_o_salon_de_belleza_o_flores_empresa_rosa_vector_logo_ilustracion_el_logotipo_simple_minimo_facil_t_2f4d9c0___copia {
            get {
                object obj = ResourceManager.GetObject("hermoso-contorno-logo-con-rosa-flor-para-boutique-o-salon-de-belleza-o-flores-emp" +
                        "resa-rosa-vector-logo-ilustracion-el-logotipo-simple-minimo-facil-t-2f4d9c0 - co" +
                        "pia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hermoso_contorno_logo_con_rosa_flor_para_boutique_o_salon_de_belleza_o_flores_empresa_rosa_vector_logo_ilustracion_el_logotipo_simple_minimo_facil_t_2f4d9mt {
            get {
                object obj = ResourceManager.GetObject("hermoso-contorno-logo-con-rosa-flor-para-boutique-o-salon-de-belleza-o-flores-emp" +
                        "resa-rosa-vector-logo-ilustracion-el-logotipo-simple-minimo-facil-t-2f4d9mt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hermoso_contorno_logo_con_rosa_flor_para_boutique_o_salon_de_belleza_o_flores_empresa_rosa_vector_logo_ilustracion_el_logotipo_simple_minimo_facil_t_2f4daax {
            get {
                object obj = ResourceManager.GetObject("hermoso-contorno-logo-con-rosa-flor-para-boutique-o-salon-de-belleza-o-flores-emp" +
                        "resa-rosa-vector-logo-ilustracion-el-logotipo-simple-minimo-facil-t-2f4daax", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hermoso_contorno_logo_con_rosa_flor_para_boutique_o_salon_de_belleza_o_flores_empresa_rosa_vector_logo_ilustracion_el_logotipo_simple_minimo_facil_t_2f4daax___copia {
            get {
                object obj = ResourceManager.GetObject("hermoso-contorno-logo-con-rosa-flor-para-boutique-o-salon-de-belleza-o-flores-emp" +
                        "resa-rosa-vector-logo-ilustracion-el-logotipo-simple-minimo-facil-t-2f4daax - co" +
                        "pia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hermoso_contorno_logo_con_rosa_flor_para_boutique_o_salon_de_belleza_o_flores_empresa_rosa_vector_logo_ilustracion_el_logotipo_simple_minimo_facil_t_2f4daax___copia1 {
            get {
                object obj = ResourceManager.GetObject("hermoso-contorno-logo-con-rosa-flor-para-boutique-o-salon-de-belleza-o-flores-emp" +
                        "resa-rosa-vector-logo-ilustracion-el-logotipo-simple-minimo-facil-t-2f4daax - co" +
                        "pia1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hermoso_contorno_logo_con_rosa_flor_para_boutique_o_salon_de_belleza_o_flores_empresa_rosa_vector_logo_ilustracion_el_logotipo_simple_minimo_facil_t_2f4daax___copia2 {
            get {
                object obj = ResourceManager.GetObject("hermoso-contorno-logo-con-rosa-flor-para-boutique-o-salon-de-belleza-o-flores-emp" +
                        "resa-rosa-vector-logo-ilustracion-el-logotipo-simple-minimo-facil-t-2f4daax - co" +
                        "pia2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hermoso_contorno_logo_con_rosa_flor_para_boutique_o_salon_de_belleza_o_flores_empresa_rosa_vector_logo_ilustracion_el_logotipo_simple_minimo_facil_t_2f4daax1 {
            get {
                object obj = ResourceManager.GetObject("hermoso-contorno-logo-con-rosa-flor-para-boutique-o-salon-de-belleza-o-flores-emp" +
                        "resa-rosa-vector-logo-ilustracion-el-logotipo-simple-minimo-facil-t-2f4daax1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hermoso_contorno_logo_con_rosa_flor_para_boutique_o_salon_de_belleza_o_flores_empresa_rosa_vector_logo_ilustracion_el_logotipo_simple_minimo_facil_t_2f4dc85 {
            get {
                object obj = ResourceManager.GetObject("hermoso-contorno-logo-con-rosa-flor-para-boutique-o-salon-de-belleza-o-flores-emp" +
                        "resa-rosa-vector-logo-ilustracion-el-logotipo-simple-minimo-facil-t-2f4dc85", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rosa_flor_logo_vector_diseno_de_plantilla_2egwwpn {
            get {
                object obj = ResourceManager.GetObject("rosa-flor-logo-vector-diseno-de-plantilla-2egwwpn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
